# Page settings

baseURL = ""
languageCode = "en"
title = ""
theme = "devresume"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Ryo Nishikawa"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
    #primaryColor = "#54B689"
    primaryColor = "#7e191b"

    [params.profile]
        enable = true
        name = "Ryo Nishikawa"
        tagline = "Computer Science Major @ University of Canterbury "
        avatar = "index.png"


    [params.contact]
        enable = true
        location = "Christchurch"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-phone-square"
        url = "tel:#"
        text = "027 436 5897 "
        [[params.contact.list]]
        style = "fas"
        icon = "fa-envelope-square"
        url = "mailto:#"
        text = "hakunishikawa@gmail.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Linux"
        [[params.skills.list.items]]
        details = "Python3"
        [[params.skills.list.items]]
        details = "Java"
        [[params.skills.list.items]]
        details = "C Language"
        [[params.skills.list.items]]
        details = "JS(NodeJS, VueJs)"
        [[params.skills.list.items]]
        details = "Oracle DB/MySQL"


        #[[params.skills.list]]
        #title = "Professional"
        #[[params.skills.list.items]]
        #details = "Strong problem solver"
        #[[params.skills.list.items]]
        #details = "Team player"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "University of Canterbury"
        dates = "2018 - present"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Japanese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "rugby"
        [[params.interests.list]]
        name = "gym"
        [[params.interests.list]]
        name = "vim"
        [[params.interests.list]]
        name = "programming competition"
        [[params.interests.list]]
        name = "touch rugby"







    [params.summary]
        enable = true
        text = "A Free and Open Source Software enthusiast, clean and efficient code freak, loves working hard, enjoys rice tea and playing piano during quiet times. Has a small homelab that functions for learning purposes that also serves as a heater during winter time."





    [params.experience]
        enable = true

        [[params.experience.list]]
        company = "private python tutor"
        #details = "System Administrator"
        dates = "2018 - Present"
        [[params.experience.list.items]]
        details = "Teaching high school student between year 11-13 about how to implement if, while and for loops work"
        [[params.experience.list.items]]
        details = "Teaching the difference between int, string and flaot types and data structures such as list, set and dictionary"
        [[params.experience.list.items]]
        details = "taught students who wanted to make a quiz app, bmi calculators using tkinter"



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = 'Rugby draw Website'
        meta = "Hobby"
        tagline = "This is concurrently ongoing project that I am working on, the current website for our local rugby matches are not that great, so I am making an website that looks much better such as you can see the draw and results for the whole season of certain club, you can search player to see who he/she plays for etc"

        [[params.projects.list]]
        title = 'Garage door opener'
        meta = "Hobby"
        tagline = "Our Landlord gave us only 1 garage door key and so my flat mate and I have created garage door opener webapp using jQuery and Python (Flask), I have also used OpenCV and raspberry camera module to check the status of the garage door"

        [[params.projects.list]]
        title = '"Footprints"Hackathon 2020 hosted by Vxt'
        meta = "Hackathon"
        tagline = "A medium sized project written in Java with a group of 6 people for SENG202 course in University of Canterbury. We had to implement SQL database for our persistent storage and JavaFx for our frontend. MVC design pattern was used to separate between business logic and the model and controller."
 
        [[params.projects.list]]
        title = 'SENG302 "TrailBlazer" (coursework)'
        meta = "Coursework"
        tagline = "Activity planner using Java Spring for the backend, VueJS for the frontend and MariaDB forthe database using REST API for communication between backend and frontend"
                
       [[params.projects.list]]
        title = "DATA301 Big Data computing (coursework) Python"
        meta = "Coursework"
        tagline = "Visualized the effect of Covid-19 on several countries using GDELT data applying K meansalgorithm to see how clusters of countries had an impact on GDELT event codes comparingwith the effect of SARS"


       [[params.projects.list]]
        title = "SENG365 peition website(VueJs,NodeJs) (coursework)"
        meta = "Coursework"
        tagline = "Petition website built top of VueJS with NodeJS on the backend featuring persistence usigMariaDB"

        [[params.projects.list]]
        title = "ENCE360 multi-thread-HTTP-downloader (coursework)"
        meta = "Coursework"
        tagline = "HTTP client which performs an HTTP1.0 query which determines the maximum byte size torequest in a partial download to a website and returns the response string. This determinesthe number of partial-content downloads is needed to execute.concurrent FIFO queue which allows multiple producers and consumers to communicate ina thread-safe way, using semaphores and mutex(s) for thread synchronization.A file downloader which merges files and removes the chunks of file."

        [[params.projects.list]]
        title = "SENG201 Project"
        meta = "Coursework"
        tagline = "First project as an introduction to Java, the goal was to make a single player game in Java with GUI and getting familiar with common design patterns such as interfaces and inheritance."

        [[params.projects.list]]
        title = "DATA201 Project"
        meta = "Coursework"
        tagline = "Group research project utilising R language to collect and analyse data on how to start a career as a Software Engineer. We also learnt how to make professional reports using LateX."

        [[params.projects.list]]
        title = "ENCE260 Project"
        meta = "Coursework"
        tagline = "Small group project in C language to create a game with single board computer UCFK4. We made a clone of snake that could move between the boards by communicating using infrared."

 
        [[params.projects.list]]
        title = "brick breaker"
        meta = "Personal project"
        tagline = "a brick breaker game to get used to know how to code in JS, it was my first time coding in jsand it was a good practice on how to get the keyboard inputs, the section of block andboarder to make sure that ball reflects the of the square and the box."




    [params.information]
        enable = true

        [[params.information.list]]
        title = "Certifications"
        [[params.information.list.items]]
        details = "2018 · SUSE Linux Enterprise Server Administrator and Engineer"
        [[params.information.list.items]]
        details = "2018 · SUSE Linux Enterprise Storage Administrator"
        [[params.information.list.items]]
        details = "2017 · Certified Openstack Administrator"

        #[[params.information.list]]
        #title = "Interests"
        #details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "//gitlab.com/kenzietandun"
        title = ""
        [[params.social.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/kenzie-tandun"
        title = ""
        [[params.social.list]]
        style = "fab"
        icon = "fa-twitter-square"
        url = "//twitter.com/kenziefcc"
        title = ""





